In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
file_path='/content/drive/MyDrive/Colab Notebooks/Files/Pakistan Largest Ecommerce Dataset.csv'
df=pd.read_csv(file_path)
from tqdm import tqdm
pd.set_option('display.float_format', lambda x: '%.3f' % x)

<ipython-input-3-2a3c79f16b3b>:3: DtypeWarning: Columns (1,2,3,7,8,9,11,12,13,14,17,18,19) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(file_path)

In [ ]:
df.head(100)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.000,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,Women's Fashion,\N,...,7.000,2016-7,7-2016,FY17,1.000,NaN,NaN,NaN,NaN,NaN
1,211133.000,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,Beauty & Grooming,\N,...,7.000,2016-7,7-2016,FY17,2.000,NaN,NaN,NaN,NaN,NaN
2,211134.000,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.000,1.000,2450.000,100147445,Women's Fashion,\N,...,7.000,2016-7,7-2016,FY17,3.000,NaN,NaN,NaN,NaN,NaN
3,211135.000,complete,7/1/2016,kcc_krone deal,360.000,1.000,60.000,100147446,Beauty & Grooming,R-FSD-52352,...,7.000,2016-7,7-2016,FY17,4.000,NaN,NaN,NaN,NaN,NaN
4,211136.000,order_refunded,7/1/2016,BK7010400AG,555.000,2.000,1110.000,100147447,Soghaat,\N,...,7.000,2016-7,7-2016,FY17,5.000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,211238.000,received,7/1/2016,kcc_glamour deal,320.000,1.000,320.000,100147515,Beauty & Grooming,C-MUX-106279,...,7.000,2016-7,7-2016,FY17,43.000,NaN,NaN,NaN,NaN,NaN
96,211239.000,complete,7/1/2016,Dany_AUK-650,4200.000,1.000,4200.000,100147516,Mobiles & Tablets,R-LHW-105666,...,7.000,2016-7,7-2016,FY17,46.000,NaN,NaN,NaN,NaN,NaN
97,211240.000,complete,7/1/2016,UK_Namkino Mix Nimco 8 Pcs Gift Pack,760.000,1.000,1195.000,100147517,Soghaat,R-KHW-104406,...,7.000,2016-7,7-2016,FY17,13.000,NaN,NaN,NaN,NaN,NaN
98,211241.000,complete,7/1/2016,RS_Chum Chum Tin,435.000,1.000,1195.000,100147517,Soghaat,R-KHW-104406,...,7.000,2016-7,7-2016,FY17,13.000,NaN,NaN,NaN,NaN,NaN
99,211242.000,complete,7/1/2016,urban_ PT004-L,550.000,1.000,550.000,100147518,\N,C-PEW-105784,...,7.000,2016-7,7-2016,FY17,47.000,NaN,NaN,NaN,NaN,NaN

In [ ]:

df.shape

(1048575, 26)

In [ ]:
df[df['item_id'].notnull()]

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Month,Customer Since,M-Y,FY,Customer ID,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,211131.000,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,Women's Fashion,\N,...,7.000,2016-7,7-2016,FY17,1.000,NaN,NaN,NaN,NaN,NaN
1,211133.000,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,Beauty & Grooming,\N,...,7.000,2016-7,7-2016,FY17,2.000,NaN,NaN,NaN,NaN,NaN
2,211134.000,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.000,1.000,2450.000,100147445,Women's Fashion,\N,...,7.000,2016-7,7-2016,FY17,3.000,NaN,NaN,NaN,NaN,NaN
3,211135.000,complete,7/1/2016,kcc_krone deal,360.000,1.000,60.000,100147446,Beauty & Grooming,R-FSD-52352,...,7.000,2016-7,7-2016,FY17,4.000,NaN,NaN,NaN,NaN,NaN
4,211136.000,order_refunded,7/1/2016,BK7010400AG,555.000,2.000,1110.000,100147447,Soghaat,\N,...,7.000,2016-7,7-2016,FY17,5.000,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584519,905204.000,cod,8/28/2018,WOFSCE5AE00357AECDE,699.000,1.000,849.000,100562385,Women's Fashion,NaN,...,8.000,2018-8,8-2018,FY19,115320.000,NaN,NaN,NaN,NaN,NaN
584520,905205.000,processing,8/28/2018,MATHUA5AF70A7D1E50A,35599.000,1.000,35899.000,100562386,Mobiles & Tablets,NaN,...,8.000,2018-8,8-2018,FY19,115326.000,NaN,NaN,NaN,NaN,NaN
584521,905206.000,processing,8/28/2018,MATSAM5B6D7208C6D30,129999.000,2.000,652178.000,100562387,Mobiles & Tablets,NaN,...,8.000,2018-7,8-2018,FY19,113474.000,NaN,NaN,NaN,NaN,NaN
584522,905207.000,processing,8/28/2018,MATSAM5B1509B4696EA,87300.000,2.000,652178.000,100562387,Mobiles & Tablets,NaN,...,8.000,2018-7,8-2018,FY19,113474.000,NaN,NaN,NaN,NaN,NaN
584523,905208.000,processing,8/28/2018,MATSAM5B10F91A9B6AB,108640.000,2.000,652178.000,100562387,Mobiles & Tablets,NaN,...,8.000,2018-7,8-2018,FY19,113474.000,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  float64
 1   status                 584509 non-null  object
 2   created_at             584524 non-null  object
 3   sku                    584504 non-null  object
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  float64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  object
 9   sales_commission_code  447346 non-null  object
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  object
 12  Working Date           584524 non-null  object
 13  BI Status              584524 non-null  object
 14   MV                    584524 non-null  object
 15  Year                   584524 non-null  float64
 16  Month                  584524 non-null  float64
 17  Customer Since         584513 non-null  object
 18  M-Y                    584524 non-null  object
 19  FY                     584524 non-null  object
 20  Customer ID            584513 non-null  float64
 21  Unnamed: 21            0 non-null       float64
 22  Unnamed: 22            0 non-null       float64
 23  Unnamed: 23            0 non-null       float64
 24  Unnamed: 24            0 non-null       float64
 25  Unnamed: 25            0 non-null       float64
dtypes: float64(13), object(13)
memory usage: 208.0+ MB

In [ ]:
#Clean Data
df = df[['item_id',
 'status',
 'created_at',
 'sku',
 'price',
 'qty_ordered',
 'grand_total',
 'increment_id',
 'category_name_1',
 'sales_commission_code',
 'discount_amount',
 'payment_method',
 'Working Date',
 'BI Status',
 ' MV ',
 'Year',
 'Month',
 'Customer Since',
 'M-Y',
 'FY',
 'Customer ID']]

In [ ]:
df = df[df['item_id'].notnull()]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 584524 entries, 0 to 584523
Data columns (total 21 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   item_id                584524 non-null  float64
 1   status                 584509 non-null  object
 2   created_at             584524 non-null  object
 3   sku                    584504 non-null  object
 4   price                  584524 non-null  float64
 5   qty_ordered            584524 non-null  float64
 6   grand_total            584524 non-null  float64
 7   increment_id           584524 non-null  object
 8   category_name_1        584360 non-null  object
 9   sales_commission_code  447346 non-null  object
 10  discount_amount        584524 non-null  float64
 11  payment_method         584524 non-null  object
 12  Working Date           584524 non-null  object
 13  BI Status              584524 non-null  object
 14   MV                    584524 non-null  object
 15  Year                   584524 non-null  float64
 16  Month                  584524 non-null  float64
 17  Customer Since         584513 non-null  object
 18  M-Y                    584524 non-null  object
 19  FY                     584524 non-null  object
 20  Customer ID            584513 non-null  float64
dtypes: float64(8), object(13)
memory usage: 98.1+ MB

In [ ]:
df.describe()

,item_id,price,qty_ordered,grand_total,discount_amount,Year,Month,Customer ID
count,584524.000,584524.000,584524.000,584524.000,584524.000,584524.000,584524.000,584513.000
mean,565667.074,6348.748,1.296,8530.619,499.493,2017.044,7.168,45790.512
std,200121.174,14949.270,3.996,61320.815,1506.943,0.707,3.486,34414.962
min,211131.000,0.000,1.000,-1594.000,-599.500,2016.000,1.000,1.000
25%,395000.750,360.000,1.000,945.000,0.000,2017.000,4.000,13516.000
50%,568424.500,899.000,1.000,1960.400,0.000,2017.000,7.000,42856.000
75%,739106.250,4070.000,1.000,6999.000,160.500,2018.000,11.000,73536.000
max,905208.000,1012625.900,1000.000,17888000.000,90300.000,2018.000,12.000,115326.000

In [ ]:
df.describe(include='O')

,status,created_at,sku,increment_id,category_name_1,sales_commission_code,payment_method,Working Date,BI Status,MV,Customer Since,M-Y,FY
count,584509,584524,584504,584524,584360,447346,584524,584524,584524,584524,584513,584524,584524
unique,16,789,84889,408785,16,7225,18,789,4,9720,26,26,3
top,complete,11/25/2016,MATSAM59DB75ADB2F80,100266667,Mobiles & Tablets,\N,cod,11/25/2016,Net,999,2016-11,11-2017,FY18
freq,233685,15169,3775,72,115710,339001,271960,15169,234178,9516,82714,83928,306883

In [ ]:
df.head(2)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131.000,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016.000,7.000,2016-7,7-2016,FY17,1.000
1,211133.000,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016.000,7.000,2016-7,7-2016,FY17,2.000

In [ ]:
df['item_id'].nunique()

584524

In [ ]:
df['item_id'] = df['item_id'].apply(lambda x: int(x))

In [ ]:
df.shape

(584524, 21)

In [ ]:
df['item_id'].nunique()

584524

In [ ]:
df['item_id'].value_counts().reset_index().sort_values(by=['item_id'])

        item_id  count
0        211131      1
73066    211133      1
389683   211134      1
389684   211135      1
389685   211136      1
...         ...    ...
194845   905204      1
194846   905205      1
194847   905206      1
194848   905207      1
584523   905208      1

[584524 rows x 2 columns]

In [ ]:
df[df['qty_ordered'] == 1000]

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
239376,507556,canceled,6/8/2017,IDROID_BALRX7-Gold,8944.000,1000.000,17888000.000,100323297,Mobiles & Tablets,\N,...,jazzwallet,6/8/2017,Gross,"8,944,000",2017.000,6.000,2016-8,6-2017,FY17,5032.000
239377,507557,canceled,6/8/2017,IDROID_BALRX7-Jet black,8944.000,1000.000,17888000.000,100323297,Mobiles & Tablets,\N,...,jazzwallet,6/8/2017,Gross,"8,944,000",2017.000,6.000,2016-8,6-2017,FY17,5032.000
239381,507561,canceled,6/8/2017,IDROID_BALRX7-Jet black,8944.000,1000.000,17888000.000,100323300,Mobiles & Tablets,\N,...,jazzvoucher,6/8/2017,Gross,"8,944,000",2017.000,6.000,2016-8,6-2017,FY17,5032.000
239382,507562,canceled,6/8/2017,IDROID_BALRX7-Gold,8944.000,1000.000,17888000.000,100323300,Mobiles & Tablets,\N,...,jazzvoucher,6/8/2017,Gross,"8,944,000",2017.000,6.000,2016-8,6-2017,FY17,5032.000
240078,508368,complete,6/9/2017,IDROID_BALRX7-Gold,8944.000,1000.000,17888000.000,100323649,Mobiles & Tablets,\N,...,jazzvoucher,6/9/2017,Net,"8,944,000",2017.000,6.000,2017-6,6-2017,FY17,50387.000
240079,508369,complete,6/9/2017,IDROID_BALRX7-Jet black,8944.000,1000.000,17888000.000,100323649,Mobiles & Tablets,\N,...,jazzvoucher,6/9/2017,Net,"8,944,000",2017.000,6.000,2017-6,6-2017,FY17,50387.000

In [ ]:
df['category_name_1'].value_counts()

category_name_1
Mobiles & Tablets     115710
Men's Fashion          92221
Women's Fashion        59721
Appliances             52413
Superstore             43613
Beauty & Grooming      41496
Soghaat                34011
Others                 29218
Home & Living          26504
Entertainment          26326
Health & Sports        17502
Kids & Baby            16494
Computing              15933
\N                      7850
School & Education      3478
Books                   1870
Name: count, dtype: int64

In [ ]:
df[df['category_name_1']=="\\N"]['sku'].value_counts()

sku
emart_00-1                          1343
Telemall_MM-DR-HB-L                  878
test-product-00                      774
test-product                         613
Infinix Hot 4 Nationwide-Gold        479
                                    ...
clickbuscollection_nwc-29-Red          1
clickbuscollection_nwc-29-Maroon       1
audionic_6954217598857                 1
clickbuscollection_nwc-33-M            1
D Lend a Helping Hand                  1
Name: count, Length: 295, dtype: int64

In [ ]:
df[df['sku']=='emart_00-1']['category_name_1'].value_counts()

category_name_1
\N        1343
Others      48
Name: count, dtype: int64

In [ ]:
temp_df = df.groupby(by=['sku'])['category_name_1'].nunique().reset_index().sort_values(by=['category_name_1'],ascending=False)

In [ ]:
temp_df.head(2)

                                         sku  category_name_1
79608  mt_Red-Battery-Case-for-iPhone-5-&-5s                2
414                  AJ-ajrak_AJA-005-Medium                2

In [ ]:
prob_skus_ls = temp_df[temp_df['category_name_1']>1]['sku'].unique().tolist()

In [ ]:
temp_df = df[df['sku'].isin(prob_skus_ls)]

In [ ]:
temp_df.groupby(by=['sku','category_name_1'])['item_id'].nunique()

sku                                    category_name_1
AJ-ajrak_AJA-005-Large                 Men's Fashion           2
                                       Women's Fashion         4
AJ-ajrak_AJA-005-Medium                Men's Fashion           1
                                       Women's Fashion         1
Dawlance_MD 10 + DWB 600               Appliances              2
                                       \N                     44
Huawei_P9Lite-Black                    Mobiles & Tablets       1
                                       \N                     88
Huawei_P9Lite-Gold                     Mobiles & Tablets       1
                                       \N                     58
JSM_JSM-001-White-Pak-Shirt-L          Men's Fashion          60
                                       \N                      4
JSM_JSM-001-White-Pak-Shirt-M          Men's Fashion          55
                                       \N                      5
JSM_JSM-002-Green-Pak-Shirt -L         Men's Fashion          81
                                       \N                      8
JSM_JSM-002-Green-Pak-Shirt -M         Men's Fashion         157
                                       \N                     15
JSM_JSM-002-Green-Pak-Shirt -S         Men's Fashion          67
                                       \N                      5
JSM_JSM-003-ComboGreenWhitePakShirt-L  Men's Fashion          93
                                       \N                     17
JSM_JSM-003-ComboGreenWhitePakShirt-M  Men's Fashion         172
                                       \N                     19
JSM_JSM-003-ComboGreenWhitePakShirt-S  Men's Fashion          52
                                       \N                      7
OTHOTH5A0945D0A72F4                    Others                508
                                       \N                    101
RB_Dettol Germ Busting Kit-bf          Superstore             13
                                       \N                    404
Regal_052-N-B-BROWN-7                  Women's Fashion         1
                                       \N                      2
airlink_huawei_Google-Nexus-6P-Silver  Mobiles & Tablets       1
                                       \N                      1
aw_PKS-0013-White-S                    Men's Fashion           2
                                       \N                      1
clickbuscollection_nwc-29-Purple       Women's Fashion         2
                                       \N                      2
clickbuscollection_nwc-29-Red          Women's Fashion         5
                                       \N                      1
emart_00-1                             Others                 48
                                       \N                   1343
mt_Red-Battery-Case-for-iPhone-5-&-5s  Mobiles & Tablets       7
                                       \N                      9
Name: item_id, dtype: int64

In [ ]:
df.head(2)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016.000,7.000,2016-7,7-2016,FY17,1.000
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016.000,7.000,2016-7,7-2016,FY17,2.000

In [ ]:
cache = []
for i in tqdm(prob_skus_ls):
  # fetch relevant sku #
  sample = df[df['sku']== i ]
  sample['New Category'] = sample['category_name_1']
  # find valid category other than backslash N #
  replace_val = sample[sample['category_name_1']!='\\N']['category_name_1'].values[0]
  # replace value where it make sense #
  sample.loc[sample['category_name_1']=="\\N",'New Category'] = replace_val

  # store back to df #
  cache.append(sample)

  0%|          | 0/22 [00:00<?, ?it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
  5%|▍         | 1/22 [00:00<00:02,  8.82it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
  9%|▉         | 2/22 [00:00<00:02,  9.13it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 14%|█▎        | 3/22 [00:00<00:02,  9.13it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 18%|█▊        | 4/22 [00:00<00:02,  8.93it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 23%|██▎       | 5/22 [00:00<00:01,  8.82it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 27%|██▋       | 6/22 [00:00<00:01,  9.15it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 32%|███▏      | 7/22 [00:00<00:01,  9.39it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 36%|███▋      | 8/22 [00:00<00:01,  9.33it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 41%|████      | 9/22 [00:00<00:01,  9.38it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 50%|█████     | 11/22 [00:01<00:01,  9.71it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 55%|█████▍    | 12/22 [00:01<00:01,  9.45it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 59%|█████▉    | 13/22 [00:01<00:00,  9.26it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 64%|██████▎   | 14/22 [00:01<00:00,  9.20it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 68%|██████▊   | 15/22 [00:01<00:00,  8.59it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 73%|███████▎  | 16/22 [00:01<00:00,  8.60it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 77%|███████▋  | 17/22 [00:01<00:00,  8.38it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 82%|████████▏ | 18/22 [00:02<00:00,  8.03it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 86%|████████▋ | 19/22 [00:02<00:00,  8.45it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 91%|█████████ | 20/22 [00:02<00:00,  8.65it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
 95%|█████████▌| 21/22 [00:02<00:00,  8.04it/s]<ipython-input-29-940286d4f18b>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sample['New Category'] = sample['category_name_1']
100%|██████████| 22/22 [00:02<00:00,  8.81it/s]

In [ ]:
len(cache)

22

In [ ]:
cache[0]

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID,New Category
264148,536179,complete,7/15/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,790.000,100336629,\N,\N,...,7/15/2017,Net,665,2017.000,7.000,2016-7,7-2017,FY18,2348.000,Mobiles & Tablets
266728,539014,complete,7/20/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,1052.000,100338075,\N,\N,...,7/20/2017,Net,665,2017.000,7.000,2017-7,7-2017,FY18,55128.000,Mobiles & Tablets
268864,541483,complete,7/24/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100339353,\N,\N,...,7/24/2017,Net,665,2017.000,7.000,2017-7,7-2017,FY18,55528.000,Mobiles & Tablets
270061,542799,order_refunded,7/26/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100339910,\N,\N,...,7/26/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,55702.000,Mobiles & Tablets
270200,542952,order_refunded,7/26/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100339963,\N,\N,...,7/26/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,55713.000,Mobiles & Tablets
270242,542997,order_refunded,7/26/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100339988,\N,\N,...,7/26/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,55724.000,Mobiles & Tablets
270770,543566,order_refunded,7/27/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100340199,\N,\N,...,7/27/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,55764.000,Mobiles & Tablets
270855,543669,complete,7/27/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100340244,\N,\N,...,7/27/2017,Net,665,2017.000,7.000,2017-7,7-2017,FY18,55778.000,Mobiles & Tablets
271997,544862,received,7/28/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100340596,\N,\N,...,7/28/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,55852.000,Mobiles & Tablets
273354,546386,complete,7/31/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100341314,Mobiles & Tablets,\N,...,7/31/2017,Net,665,2017.000,7.000,2017-7,7-2017,FY18,56088.000,Mobiles & Tablets
273690,546752,complete,7/31/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100341501,Mobiles & Tablets,\N,...,7/31/2017,Net,665,2017.000,7.000,2017-7,7-2017,FY18,56146.000,Mobiles & Tablets
273913,546985,order_refunded,7/31/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100341590,Mobiles & Tablets,\N,...,7/31/2017,Valid,665,2017.000,7.000,2017-7,7-2017,FY18,56176.000,Mobiles & Tablets
277288,551437,complete,8/4/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100343300,Mobiles & Tablets,\N,...,8/4/2017,Net,665,2017.000,8.000,2017-8,8-2017,FY18,56643.000,Mobiles & Tablets
278531,553136,received,8/7/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,2.000,1330.000,100343931,Mobiles & Tablets,\N,...,8/7/2017,Valid,"1,330",2017.000,8.000,2017-8,8-2017,FY18,56891.000,Mobiles & Tablets
278587,553223,complete,8/7/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100343960,Mobiles & Tablets,\N,...,8/7/2017,Net,665,2017.000,8.000,2017-6,8-2017,FY18,52085.000,Mobiles & Tablets
278589,553217,order_refunded,8/7/2017,mt_Red-Battery-Case-for-iPhone-5-&-5s,665.000,1.000,815.000,100343957,Mobiles & Tablets,\N,...,8/7/2017,Valid,665,2017.000,8.000,2017-6,8-2017,FY18,52085.000,Mobiles & Tablets

In [ ]:
prob_sku_df = pd.concat(cache, ignore_index=False)

In [ ]:
prob_sku_df.shape

(3470, 22)

In [ ]:
df.shape

(584524, 21)

In [ ]:
prob_sku_df['category_name_1'] = prob_sku_df['New Category']
prob_sku_df = prob_sku_df.drop(columns=['New Category'])

In [ ]:
prob_sku_df.shape

(3470, 21)

In [ ]:
df = df[~df['sku'].isin(prob_skus_ls)]

In [ ]:
final_df = pd.concat([df, prob_sku_df], ignore_index=False)

In [ ]:
final_df.groupby(by=['sku'])['category_name_1'].nunique().sort_values(ascending=False)

sku
AJ-ajrak_AJA-005-Medium    2
AJ-ajrak_AJA-005-Large     2
 Huawei Mate 8             1
SMSM_2703076               1
SMSM_2703187               1
                          ..
MEFQMO5A963699761E6        0
MEFQMO5A963699BA878        0
MATHAP5A698AF771FCD        0
KABASA5ABC763F62E76        0
COMWD5AA8FF5851E73         0
Name: category_name_1, Length: 84889, dtype: int64

In [ ]:
new_df = df[['sku','category_name_1']]

In [ ]:
new_df.drop_duplicates().sort_values(by=['sku'])

                                                sku    category_name_1
19328                                 Huawei Mate 8  Mobiles & Tablets
122484   MHS_Kiss Bed Set-Bed Sheet - [Size] Double      Home & Living
289174                         jjp_15000006-100-NIL  Beauty & Grooming
257122                20-herbal_Face Cleaner Lotion  Beauty & Grooming
47174                            20-herbal_Hair Oil    Health & Sports
...                                             ...                ...
16267                                  zuni16_315-A    Women's Fashion
16837                                  zuni16_317-A    Women's Fashion
18223                                  zuni16_319-A    Women's Fashion
14846                                           NaN                 \N
325391                                          NaN      Entertainment

[84873 rows x 2 columns]

In [ ]:
df.shape

(581054, 21)

In [ ]:
new_df=new_df[new_df['category_name_1'] != '\\N']

In [ ]:
new_df.head()

                                                 sku    category_name_1
0                                  kreations_YI 06-L    Women's Fashion
1  kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...  Beauty & Grooming
2                                 Ego_UP0017-999-MR0    Women's Fashion
3                                     kcc_krone deal  Beauty & Grooming
4                                        BK7010400AG            Soghaat

In [ ]:
new_df=pd.merge(new_df, new_df, left_on='sku', right_on='sku',how='left')

In [ ]:
new_df=df.drop(columns=['category_name_1'], axis=1)

In [ ]:
new_df.rename(columns={'category_name_1_y':'category_name_1'}, inplace=True)

In [ ]:
new_df.describe()

,item_id,price,qty_ordered,grand_total,discount_amount,Year,Month,Customer ID
count,581054.000,581054.000,581054.000,581054.000,581054.000,581054.000,581054.000,581043.000
mean,566307.176,6377.191,1.285,8569.581,500.210,2017.046,7.161,45906.065
std,199968.403,14983.485,3.690,61500.095,1506.663,0.707,3.488,34424.114
min,211131.000,0.000,1.000,-1594.000,-599.500,2016.000,1.000,1.000
25%,396222.500,360.000,1.000,949.000,0.000,2017.000,4.000,13575.000
50%,569686.500,905.000,1.000,1981.000,0.000,2017.000,7.000,43022.000
75%,739527.750,4199.000,1.000,7047.000,159.800,2018.000,11.000,73688.000
max,905208.000,1012625.900,1000.000,17888000.000,90300.000,2018.000,12.000,115326.000

In [ ]:
new_df.head(2)

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,sales_commission_code,discount_amount,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,\N,0.000,cod,7/1/2016,#REF!,"1,950",2016.000,7.000,2016-7,7-2016,FY17,1.000
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,\N,0.000,cod,7/1/2016,Gross,240,2016.000,7.000,2016-7,7-2016,FY17,2.000

In [ ]:
df.pivot_table(index='sku', columns=['category_name_1'], values='price', aggfunc='sum')

category_name_1,Appliances,Beauty & Grooming,Books,Computing,Entertainment,Health & Sports,Home & Living,Kids & Baby,Men's Fashion,Mobiles & Tablets,Others,School & Education,Soghaat,Superstore,Women's Fashion,\N
sku,,,,,,,,,,,,,,,,
Huawei Mate 8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,549990.000,NaN,NaN,NaN,NaN,NaN,NaN
MHS_Kiss Bed Set-Bed Sheet - [Size] Double,NaN,NaN,NaN,NaN,NaN,NaN,1590.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
jjp_15000006-100-NIL,NaN,9855.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-herbal_Face Cleaner Lotion,NaN,1312.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20-herbal_Hair Oil,NaN,NaN,NaN,NaN,NaN,4114.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuni16_314-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2275.000,NaN
zuni16_314-B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4550.000,NaN
zuni16_315-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2275.000,NaN
zuni16_317-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4550.000,NaN
zuni16_319-A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2275.000,NaN

In [ ]:
df.dropna()

,item_id,status,created_at,sku,price,qty_ordered,grand_total,increment_id,category_name_1,sales_commission_code,...,payment_method,Working Date,BI Status,MV,Year,Month,Customer Since,M-Y,FY,Customer ID
0,211131,complete,7/1/2016,kreations_YI 06-L,1950.000,1.000,1950.000,100147443,Women's Fashion,\N,...,cod,7/1/2016,#REF!,"1,950",2016.000,7.000,2016-7,7-2016,FY17,1.000
1,211133,canceled,7/1/2016,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,240.000,1.000,240.000,100147444,Beauty & Grooming,\N,...,cod,7/1/2016,Gross,240,2016.000,7.000,2016-7,7-2016,FY17,2.000
2,211134,canceled,7/1/2016,Ego_UP0017-999-MR0,2450.000,1.000,2450.000,100147445,Women's Fashion,\N,...,cod,7/1/2016,Gross,"2,450",2016.000,7.000,2016-7,7-2016,FY17,3.000
3,211135,complete,7/1/2016,kcc_krone deal,360.000,1.000,60.000,100147446,Beauty & Grooming,R-FSD-52352,...,cod,7/1/2016,Net,360,2016.000,7.000,2016-7,7-2016,FY17,4.000
4,211136,order_refunded,7/1/2016,BK7010400AG,555.000,2.000,1110.000,100147447,Soghaat,\N,...,cod,7/1/2016,Valid,"1,110",2016.000,7.000,2016-7,7-2016,FY17,5.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584429,905105,canceled,8/28/2018,BAGPRO5B0FA123819C4,490.000,1.000,2722.000,100562312,Beauty & Grooming,100559728,...,Payaxis,8/28/2018,Gross,490,2018.000,8.000,2018-8,8-2018,FY19,114788.000
584430,905106,canceled,8/28/2018,BAGFT5A3272925D642,224.000,1.000,2722.000,100562312,Beauty & Grooming,100559728,...,Payaxis,8/28/2018,Gross,224,2018.000,8.000,2018-8,8-2018,FY19,114788.000
584431,905107,canceled,8/28/2018,FAI5A95000195701,299.000,2.000,2722.000,100562312,Superstore,100559728,...,Payaxis,8/28/2018,Gross,598,2018.000,8.000,2018-8,8-2018,FY19,114788.000
584480,905160,cod,8/28/2018,MATHUA5AE4D132A2D5A,21599.000,1.000,21899.000,100562351,Mobiles & Tablets,C-PEW-112010,...,cod,8/28/2018,Valid,"21,599",2018.000,8.000,2018-5,8-2018,FY19,106822.000
584491,905171,processing,8/28/2018,MATAPP59AD3CFE4A7CA,44459.000,1.000,44759.000,100562360,Mobiles & Tablets,111066,...,cod,8/28/2018,Gross,"44,459",2018.000,8.000,2017-11,8-2018,FY19,67562.000

Melt

In [ ]:
#te=df.melt(id_vars==['sku'], value_vars==['category_name_1'])

In [ ]:
#temp=merged_df.melt(id_vars==['category_name'])
#temp[temp['category_name']=="Women's Fashion"]

In [ ]:
df.melt(id_vars=['sku'], value_vars=['category_name_1'])

,sku,variable,value
0,kreations_YI 06-L,category_name_1,Women's Fashion
1,kcc_Buy 2 Frey Air Freshener & Get 1 Kasual Bo...,category_name_1,Beauty & Grooming
2,Ego_UP0017-999-MR0,category_name_1,Women's Fashion
3,kcc_krone deal,category_name_1,Beauty & Grooming
4,BK7010400AG,category_name_1,Soghaat
...,...,...,...
581049,WOFSCE5AE00357AECDE,category_name_1,Women's Fashion
581050,MATHUA5AF70A7D1E50A,category_name_1,Mobiles & Tablets
581051,MATSAM5B6D7208C6D30,category_name_1,Mobiles & Tablets
581052,MATSAM5B1509B4696EA,category_name_1,Mobiles & Tablets
581053,MATSAM5B10F91A9B6AB,category_name_1,Mobiles & Tablets

In [ ]:
#df.melt(id_vars=['sku'], value_vars=['category_name_1','Customer Id'])

In [ ]:
df.shape

(581054, 21)

In [ ]:
agg_df=df.groupby(by=['sku','category_name_1'])['price'].sum().reset_index()

In [ ]:
agg_df=df.groupby(by=['category_name_1'])['price'].sum().reset_index()

In [ ]:
agg_df.rename(columns={'category_name_1_x':'category_name'},inplace=True)

In [ ]:
agg_df

       category_name_1          price
0           Appliances  579588159.230
1    Beauty & Grooming   36490216.750
2                Books     904314.000
3            Computing  173428070.690
4        Entertainment  506933120.860
5      Health & Sports   17847774.390
6        Home & Living   29971858.570
7          Kids & Baby   11098938.350
8        Men's Fashion   83605093.370
9    Mobiles & Tablets 2029979180.960
10              Others   64957899.000
11  School & Education    1676904.290
12             Soghaat   10006560.100
13          Superstore   26631512.420
14     Women's Fashion  104985045.910
15                  \N   27361865.640

In [ ]:
fig, ax = plt.subplots(figsize=(10, 5))
sns.barplot(data=agg_df,y='category_name_1', x='price', ax=ax)

NameError: name 'plt' is not defined

WEEK 6

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [ ]:
df.head(2)

In [ ]:
plt.hist(df['price'])
plt.title('Distribution of Price')
plt.show

In [ ]:
sample_df=df[df['price']<4070]

In [ ]:
plt.hist(sample_df['price'])
plt.title('Distribution of Price')
plt.show

In [ ]:
agg=sample_df.groupby(by=['category_name_1'])['price'].mean().reset_index().sort_values(by=['price'],ascending=False)
agg

In [ ]:
fig,ax=plt.subplots(figsize=(15,5))
sns.boxplot(x='category_name_1',data=df, y='price', ax=ax)
plt.xticks(rotation=90)
plt.show

In [ ]:
fig, ax=plt.subplots(figsize=(15,5))
sns.boxplot(x='category_name_1',data=sample_df, y='price', ax=ax)
plt.title('Price Distribution of Categories')
plt.xticks(rotation=90)
plt

In [ ]:
sample_df.head(2)

In [ ]:
sample_df['status'].value_counts()

In [ ]:
comp_status_df=sample_df[sample_df['status']=='complete']
sample_df=sample_df.sort_values(by=['category_name_1'])

In [ ]:
fig,ax=plt.subplots(ncols=2,figsize=(15,7))
sns.boxplot(x='category_name_1',data=comp_status_df, y='price', ax=ax[0])
sns.boxplot(x='category_name_1',data=sample_df, y='price', ax=ax[1])
#plt.title('Price Distribution of Categories')
ax[0].tick_params(axis='x',rotation=90)
ax[1].tick_params(axis='x',rotation=90)
plt.show()

In [ ]:
sample_df=sample_df[['category_name_1','price']]
sample_df['flag']='all status'

In [ ]:
sample_df.head(2)

In [ ]:
comp_status_df=comp_status_df[['category_name_1','price']]
comp_status_df['flag']='complete'

In [ ]:
comp_status_df.rename(columns={'category_name_1':'complete'})

In [ ]:
combine_df=pd.concat([sample_df,comp_status_df],ignore_index=True)

In [ ]:
combine_df

In [ ]:
fig,ax=plt.subplots(figsize=(15,5))
sns.boxplot(x='category_name_1',data=combine_df, y='price', hue='flag',ax=ax)
plt.title('Price Distribution of Categories')
plt.xticks(rotation=90)
plt

In [ ]:
df.head(2)

In [ ]:
df.groupby(by=['category_name_1'])['qty_ordered'].mean().sort_values(ascending=False)

In [ ]:
df['item_id'].value_counts()

In [ ]:
df['increment_id'].describe()

In [ ]:
agg=df.groupby(by=['Month'])['Customer ID'].size().reset_index()

In [ ]:
agg.head(2)

In [ ]:
fig,ax=plt.subplots(figsize=(10,5))
#sns.scatterplot(x='Month',y='Customer ID',data=df,ax=ax)
sns.scatterplot(x='price',y='qty_ordered', hue='category_name_1',data=df,ax=ax)
#

In [ ]:
sample=df[df['price']<5000]

In [ ]:
fig,ax=plt.subplots(figsize=(10,5))
sns.scatterplot(x='price',y='qty_ordered', hue='category_name_1',data=sample,ax=ax)